- hosts: desktop, alt_desktop
  gather_facts: true
  roles:
  - UniInc.Gnome-Ergonomic-tweaks
  - UniInc.Barrier-meta

- hosts: desktop
  vars:
    barrier_role: client
  roles:
  - UniInc.Barrier-config

- hosts: alt_desktop
  vars:
    barrier_role: server
  roles:
  - UniInc.Barrier-config
