- hosts: desktop, test
  gather_facts: true
  roles:
  - UniInc.Gnome-Ergonomic-tweaks
  - ansible-role-Barrier-mouse-keyboard
  - ansible-role-Barrier-OpenSSL

- hosts: desktop
  vars:
    barrier_role: server
  roles:
  - ansible-role-Barrier-config

- hosts: test
  vars:
    barrier_role: client
  roles:
  - ansible-role-Barrier-config
